apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cashonrails-api-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/iampryce/my-assessment-api
    targetRevision: main
    path: deploy/helm/cashonrails-api
    helm:
      valueFiles:
        - values.yaml
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: cashonrails
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
