apiVersion: v1
kind: Service
metadata:
  name: cashonrails-api
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cashonrails-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "cashonrails-api.labels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
